<a href="https://colab.research.google.com/github/aynandu/Python-DeepLearning/blob/master/00_pytoruch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**00-Pytourch Fundamentals**

Resource Book : https://www.learnpytorch.io/00_pytorch_fundamentals/
Questions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


ModuleNotFoundError: No module named 'pandas'

#Introduction to Tensors

###Creating tensors

PyTorch Tensors are Created Using 'torch.tensor()' : - https://pytorch.org/docs/stable/tensors.html

Tensor : - https://en.wikipedia.org/wiki/Tensor

#scalar = 1 ,
#Vector =
        [
          1
          2]
#matrix =
      [
          1 2
          3 4
              ]
#tesnor =
      [
          [1 2] [3 2]
          [1 7] [5 4]
                    ]

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
#ndimention - scalar
scalar.ndim

0

In [ ]:
#Size
scalar.shape

torch.Size([])

In [ ]:
#Get Tensor Back as Python int
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#ndimention - Vector
vector.ndim

1

In [ ]:
#size
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX =torch.tensor([[7,8],
                      [9,10],
                      [11,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
#ndimentions
MATRIX.ndim


2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
#Size
MATRIX.shape

torch.Size([3, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,3,8]]])
TENSOR
#pink parent has 1 child "blue"; blue parent has 4 (column) child "yellow";each yellow having 3 (row) child values. it becomes shape of (1,4,3)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [1, 3, 8]]])

In [ ]:
#ndimenstion
TENSOR.ndim

3

In [ ]:
#Size
TENSOR.shape

torch.Size([1, 4, 3])

#**Random Tensors**

###*Why random tensors?*
#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers better represent the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
#Create A Random Matric of size
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.9029, 0.4211, 0.6514, 0.1314],
         [0.8016, 0.1496, 0.3662, 0.5450],
         [0.4964, 0.6579, 0.1088, 0.0827]],

        [[0.8435, 0.5802, 0.1586, 0.4948],
         [0.1714, 0.9427, 0.7082, 0.5880],
         [0.1312, 0.2080, 0.1911, 0.0412]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#Create a random tensor with  similar shape to an image tensor
rndm_image_size_tensor = torch.rand(size=(224,224,3)) #height ,width , color Channel (R,G,B)
rndm_image_size_tensor.shape ,rndm_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and Ones

In [ ]:
#Create a tensor  of all Zeros
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
print(random_tensor.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


Create a range of tensor and tensors - like

In [7]:
#use torch.arange()
#torch.range() is also having same function but it will be removed in upcoming updates use torch.arange() instead of that.
range_Num=torch.arange(start=0,end=1000,step=50) # no step means default step is 1
range_Num

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [8]:
# Creating a tensors like 
ten_zeros=torch.zeros_like(input=range_Num)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Data Types

`Note : Tensor data type is the one of the 3 big errors you'll run into with Pytorch & Deep Learning`
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precesion in Computing : https://en.wikipedia.org/wiki/Precision_(computer_science)

In [11]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float32,# what datatype is the tensro (eg: float16,float32,float64)
                               device=None, #cpu,gpu,cuda
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [12]:
float_32_tensor.dtype

torch.float32

In [14]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [17]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
print(int_32_tensor)
value= float_32_tensor * int_32_tensor
print (f"value is {value} data type is {value.dtype}")

tensor([3, 6, 9], dtype=torch.int32)
value is tensor([ 9., 36., 81.]) data type is torch.float32


Get information from tensors (tensor attribute)

1. tensor not right datatype -  to  get datatype from a tensor, can use  `tensor.dtype`
2. tensor not right shape -  to  get shape from a tensor, can use  `tensor.shape`
1. tensor not on the right device -  to get device  from a tensor, can use  `tensor.device`

In [18]:
# Create a random tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4146, 0.8710, 0.0081, 0.7010],
        [0.1685, 0.8250, 0.0849, 0.5011],
        [0.8872, 0.0471, 0.5013, 0.4929]])

In [21]:
#Find out details about Some Tensor
print(f"Data Type : {some_tensor.dtype} | Shape : {some_tensor.shape} | Size : {some_tensor.size} |  Device : {some_tensor.device}")
# NB: some_tensor.size is a fun not attribute

Data Type : torch.float32 | Shape : torch.Size([3, 4]) | Size : <built-in method size of Tensor object at 0x0000023C74F3A8A0> |  Device : cpu


Maaipulating Tensor (tensor operations)

Tensor operations include : 
* Addition
* Subtraction
* Multiplication (Element-wise)
* Division
* Matrix multplication



In [30]:
# Create a Tensor
tensor_manip = torch.tensor([2,4,10])
print(tensor_manip)
# Addition
print("\n Addition : " , tensor_manip+10)
# Multiply
print("\n Multiply : " , tensor_manip*10)
#Subtract
print("\n Subtract : " , tensor_manip-10)

tensor([ 2,  4, 10])

 Addition :  tensor([12, 14, 20])

 Multiply :  tensor([ 20,  40, 100])

 Subtract :  tensor([-8, -6,  0])


In [33]:
# Try out with PyTorch in-built function
# Addition
print("\n Addition : " , torch.add(tensor_manip,10))
# Subtract
print("\n Subtract : " , torch.sub(tensor_manip,10))
# Multiply
print("\n Multiply : " ,  torch.mul(tensor_manip,10))


 Addition :  tensor([12, 14, 20])

 Subtract :  tensor([-8, -6,  0])

 Multiply :  tensor([ 20,  40, 100])


Matrix Multiplication

Two main ways of performing Multiplication in neural networks and deep learning

1. Element - wise multiplication
2. Matrix multiplication (dot product)

More Infromation on Multiplying Matrices : https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [36]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])
print(tensor, "*" , tensor)
print("Equals = ",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals =  tensor([1, 4, 9])
