<a href="https://colab.research.google.com/github/aynandu/Python-DeepLearning/blob/master/00_PyTorch_Fundamentals_Excercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. PyTorch Fundamentals Excercises

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

In [4]:
#2.Create a random tensor with shape (7, 7).
import torch
torch.rand(7,7)

tensor([[0.2605, 0.4224, 0.4483, 0.8592, 0.8103, 0.8882, 0.5763],
        [0.2960, 0.1957, 0.2141, 0.9115, 0.5196, 0.0666, 0.7042],
        [0.5751, 0.3426, 0.2101, 0.9020, 0.4760, 0.7934, 0.3291],
        [0.1195, 0.0695, 0.3757, 0.4808, 0.1702, 0.5446, 0.8017],
        [0.2104, 0.4674, 0.6278, 0.6627, 0.7819, 0.7609, 0.9885],
        [0.7451, 0.4811, 0.1169, 0.7727, 0.1242, 0.1246, 0.7639],
        [0.3152, 0.7196, 0.1978, 0.8610, 0.9562, 0.9568, 0.2788]])

In [11]:
#3.Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
tensor_one=torch.rand(1,7)
tensor_two=torch.rand(1,7)
print(f"Multipy Rows and Columns into single value:\n {torch.matmul(tensor_one,tensor_two.T)} \nMultiply each row, colum with another : \n {torch.mul(tensor_one,tensor_two.T)}")

Multipy Rows and Columns into single value:
 tensor([[1.8602]]) 
Multiply each row, colum with another : 
 tensor([[0.1994, 0.0684, 0.1027, 0.1351, 0.0454, 0.1694, 0.1481],
        [0.0724, 0.0248, 0.0373, 0.0490, 0.0165, 0.0615, 0.0538],
        [0.7880, 0.2701, 0.4059, 0.5340, 0.1794, 0.6695, 0.5854],
        [0.6951, 0.2383, 0.3581, 0.4710, 0.1583, 0.5905, 0.5164],
        [0.3677, 0.1261, 0.1894, 0.2492, 0.0837, 0.3124, 0.2732],
        [0.3492, 0.1197, 0.1799, 0.2366, 0.0795, 0.2966, 0.2594],
        [0.5098, 0.1747, 0.2626, 0.3454, 0.1161, 0.4331, 0.3787]])


In [19]:
#4. Set the random seed to 0 and do exercises 2 & 3 over again.
random_seed=0
#Ex - 2
torch.manual_seed(random_seed)
print(f"Random_Seed for Excercise 2: \n{torch.rand(7,7)}")

#Ex - 3
torch.manual_seed(random_seed)
tensor_one=torch.rand(1,7)
torch.manual_seed(random_seed)
tensor_two=torch.rand(1,7)
print(f"\n{tensor_two==tensor_one}\n")
print(f"Excercise 3 with random Seed : - Multipy Rows and Columns into single value:\n {torch.matmul(tensor_one,tensor_two.T)} \nMultiply each row, colum with another : \n {torch.mul(tensor_one,tensor_two.T)}")

Random_Seed for Excercise 2: 
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

tensor([[True, True, True, True, True, True, True]])

Excercise 3 with random Seed : - Multipy Rows and Columns into single value:
 tensor([[1.5985]]) 
Multiply each row, colum with another : 
 tensor([[0.2463, 0.3812, 0.0439, 0.0655, 0.1526, 0.3147, 0.2432],
        [0.3812, 0.5902, 0.0680, 0.1014, 0.2362, 0.4871, 0.3765],
        [0.0439, 0.0680, 0.0078, 0.0117, 0.0272, 0.0561, 0.0434],
        [0.0655, 0.1014, 0.0117, 0.0174, 0.0406, 0.0837, 0.0647],
        [0.1526, 0.2362, 0.0272, 0.0406, 0.0945,