<a href="https://colab.research.google.com/github/aynandu/Python-DeepLearning/blob/master/00_pytoruch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**00-Pytourch Fundamentals**

Resource Book : https://www.learnpytorch.io/00_pytorch_fundamentals/
Questions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
#import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cpu


#Introduction to Tensors

###Creating tensors

PyTorch Tensors are Created Using 'torch.tensor()' : - https://pytorch.org/docs/stable/tensors.html

Tensor : - https://en.wikipedia.org/wiki/Tensor

#scalar = 1 ,
#Vector =
        [
          1
          2]
#matrix =
      [
          1 2
          3 4
              ]
#tesnor =
      [
          [1 2] [3 2]
          [1 7] [5 4]
                    ]

In [3]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
#ndimention - scalar
scalar.ndim

0

In [5]:
#Size
scalar.shape

torch.Size([])

In [6]:
#Get Tensor Back as Python int
scalar.item()

7

In [7]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
#ndimention - Vector
vector.ndim

1

In [9]:
#size
vector.shape

torch.Size([2])

In [10]:
#Matrix
MATRIX =torch.tensor([[7,8],
                      [9,10],
                      [11,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [11]:
#ndimentions
MATRIX.ndim


2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
#Size
MATRIX.shape

torch.Size([3, 2])

In [14]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,3,8]]])
TENSOR
#pink parent has 1 child "blue"; blue parent has 4 (column) child "yellow";each yellow having 3 (row) child values. it becomes shape of (1,4,3)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [1, 3, 8]]])

In [15]:
#ndimenstion
TENSOR.ndim

3

In [16]:
#Size
TENSOR.shape

torch.Size([1, 4, 3])

#**Random Tensors**

###*Why random tensors?*
#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers better represent the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
#Create A Random Matric of size
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.8938, 0.8560, 0.5931, 0.6051],
         [0.4005, 0.8497, 0.2522, 0.4007],
         [0.8009, 0.4471, 0.0721, 0.5989]],

        [[0.1610, 0.7024, 0.0730, 0.6089],
         [0.2306, 0.4590, 0.5214, 0.1349],
         [0.6900, 0.4930, 0.3704, 0.4179]]])

In [18]:
random_tensor.ndim

3

In [19]:
#Create a random tensor with  similar shape to an image tensor
rndm_image_size_tensor = torch.rand(size=(224,224,3)) #height ,width , color Channel (R,G,B)
rndm_image_size_tensor.shape ,rndm_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and Ones

In [20]:
#Create a tensor  of all Zeros
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
print(random_tensor.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


Create a range of tensor and tensors - like

In [23]:
#use torch.arange()
#torch.range() is also having same function but it will be removed in upcoming updates use torch.arange() instead of that.
range_Num=torch.arange(start=0,end=1000,step=50) # no step means default step is 1
range_Num

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [24]:
# Creating a tensors like 
ten_zeros=torch.zeros_like(input=range_Num)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Data Types

`Note : Tensor data type is the one of the 3 big errors you'll run into with Pytorch & Deep Learning`
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precesion in Computing : https://en.wikipedia.org/wiki/Precision_(computer_science)

In [25]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float32,# what datatype is the tensro (eg: float16,float32,float64)
                               device=None, #cpu,gpu,cuda
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
print(int_32_tensor)
value= float_32_tensor * int_32_tensor
print (f"value is {value} data type is {value.dtype}")

tensor([3, 6, 9], dtype=torch.int32)
value is tensor([ 9., 36., 81.]) data type is torch.float32


Get information from tensors (tensor attribute)

1. tensor not right datatype -  to  get datatype from a tensor, can use  `tensor.dtype`
2. tensor not right shape -  to  get shape from a tensor, can use  `tensor.shape`
1. tensor not on the right device -  to get device  from a tensor, can use  `tensor.device`

In [29]:
# Create a random tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5039, 0.9382, 0.5554, 0.8323],
        [0.9079, 0.3215, 0.6800, 0.7632],
        [0.1075, 0.3631, 0.5416, 0.3393]])

In [30]:
#Find out details about Some Tensor
print(f"Data Type : {some_tensor.dtype} | Shape : {some_tensor.shape} | Size : {some_tensor.size} |  Device : {some_tensor.device}")
# NB: some_tensor.size is a fun not attribute

Data Type : torch.float32 | Shape : torch.Size([3, 4]) | Size : <built-in method size of Tensor object at 0x00000211C48155E0> |  Device : cpu


Maaipulating Tensor (tensor operations)

Tensor operations include : 
* Addition
* Subtraction
* Multiplication (Element-wise)
* Division
* Matrix multplication



In [31]:
# Create a Tensor
tensor_manip = torch.tensor([2,4,10])
print(tensor_manip)
# Addition
print("\n Addition : " , tensor_manip+10)
# Multiply
print("\n Multiply : " , tensor_manip*10)
#Subtract
print("\n Subtract : " , tensor_manip-10)

tensor([ 2,  4, 10])

 Addition :  tensor([12, 14, 20])

 Multiply :  tensor([ 20,  40, 100])

 Subtract :  tensor([-8, -6,  0])


In [32]:
# Try out with PyTorch in-built function
# Addition
print("\n Addition : " , torch.add(tensor_manip,10))
# Subtract
print("\n Subtract : " , torch.sub(tensor_manip,10))
# Multiply
print("\n Multiply : " ,  torch.mul(tensor_manip,10))


 Addition :  tensor([12, 14, 20])

 Subtract :  tensor([-8, -6,  0])

 Multiply :  tensor([ 20,  40, 100])


Matrix Multiplication

Two main ways of performing Multiplication in neural networks and deep learning

1. Element - wise multiplication
2. Matrix multiplication (dot product)

More Infromation on Multiplying Matrices : https://www.mathsisfun.com/algebra/matrix-multiplying.html

and https://www.matrixmultiplication.xyz

There are two main rules that performing matrix multiplication to satisfy : 
1. The **inner dimension** must Match :
    * (3,2) @ (3,2) won't work  --> inner dimension  2 (columns) x 3 (rows)
    * (2,3) @ (3,2) will work   --> inner dimension  3 (columns) x 3 (rows)
    * (3,2) @ (2,3) will work   --> inner dimension  2 (columns) x 2 (rows)
2. The resulting Matrixs have he shape of the **outer dimensions** :
    * (2,3) @ (3,2) will work   --> outer dimension  2 (rows) x 2 (columns)
    * (3,2) @ (2,3) will work   --> outer dimension  3 (rows) x 3 (columns)

In [33]:
print("Normal random Matrix :\n",torch.rand(3,5))
print("\nResulting Matrix :")
torch.matmul(torch.rand(3,5),torch.rand(5,3)) #The resulting Matrixs have he shape of the **outer dimensions** :

Normal random Matrix :
 tensor([[0.5639, 0.4919, 0.6971, 0.4261, 0.5554],
        [0.6911, 0.7193, 0.2680, 0.1965, 0.5465],
        [0.2205, 0.1492, 0.0533, 0.5625, 0.8992]])

Resulting Matrix :


tensor([[1.5155, 1.9095, 1.9760],
        [0.8197, 1.2377, 1.0084],
        [0.9577, 1.8182, 1.3424]])

In [34]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])
print(tensor, "*" , tensor)
print("Equals = ",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals =  tensor([1, 4, 9])


In [35]:
#Matrix Multiplication
print (torch.matmul(tensor,tensor))
print (torch.dot(tensor,tensor))

tensor(14)
tensor(14)


In [36]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2.99 ms


In [37]:
%%time
print(torch.matmul(tensor,tensor))

tensor(14)
CPU times: total: 0 ns
Wall time: 1.35 ms


One of the Common Errors in deep Learning : shape Errors

In [38]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])   
torch.mm(tensor_A,tensor_B) #torch.mm is torch.matmul      
# Cell No:27 - Error 2-- shape error               

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To Fix our tensor shape issues , we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
torch.mm(tensor_A,tensor_B.T) , torch.mm(tensor_A,tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [ ]:
# Matrix Multiplication works when tensor_B is transposed :
print(f"Orginal Shapes: tensor_A = {tensor_A.shape} tensor_B = {tensor.shape}")
print(f"New Shapes: tensor_A ={tensor_A.shape} (same as above) tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <-- Inner dimension must match")
print("\nOutput")
output= torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"\nOut Shape  : {output.shape}")

Orginal Shapes: tensor_A = torch.Size([3, 2]) tensor_B = torch.Size([3])
New Shapes: tensor_A =torch.Size([3, 2]) (same as above) tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <-- Inner dimension must match

Output
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Out Shape  : torch.Size([3, 3])


Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a Tensor 
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find Max & Min ,sum
print(f"min : {torch.min(x)}\nMax : {torch.max(x)} \nsum {torch.sum(x)} also use this method {x.sum()}")

min : 0
Max : 90 
sum 450 also use this method 450


In [ ]:
#Find Mean -  note : the torch.mean() function requires a tensor of float32 datatype to work 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
#print(f"mean: {torch.mean(x)}") --> Error : mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

# Cell No:27 - Error 1- Right Data Type error 

(tensor(45.), tensor(45.))

Finding the Positional min and max

In [ ]:
#find the position in tensor  that has the minimum value with argmin() --> returns index position of target tensor wehere the minimum value occurs
print(x.argmin(),x[0])
#find the position in tensor  that has the maximum value with argmin() --> returns index position of target tensor wehere the maximum value occurs
print(x.argmax(),x[9])

tensor(0) tensor(0)
tensor(9) tensor(90)


**Reshaping , stacking , squeezing and unsqueezing tensors**

* Reshaping - reshapes an input tensor to a defined shape
* View  - Return a view of an input tensor of certain shape but keep the same memory as the Orginal tensor.
* Stacking - Combine multiple tensors on the top of each other (vstack) or side by side (hstack); 
    * torch.stack :- https://pytorch.org/docs/stable/generated/torch.stack.html
    * Vstack :- https://pytorch.org/docs/stable/generated/torch.vstack.html   (Stack tensors in sequence vertically (row wise).)
    * hstack :- https://pytorch.org/docs/stable/generated/torch.hstack.html   (Stack tensors in sequence horizontally (column wise).)

* Squeeze - removes all 1 dimensions from a tensor ; https://pytorch.org/docs/stable/generated/torch.squeeze.html
* Unsqueeze - Add a 1 domension to a target tensor
* Permute - Return  a View of the input with dimensions permuted (swapped) in a certain way


* രീഷേപ് - ഇന്പുട്ട് ടെൻസർ ഒരു നിർവ്വചിത ആകർഷണത്തിലേക്ക് രീഷേപ് ചെയ്യുന്നു
* വ്യൂ - ഒരു ഇൻപുട്ട് ടെൻസർ നിരീക്ഷണരൂപത്തിൽ ഒരു കൊടുത്ത ആകർഷണം ലഭിക്കുന്നു, പക്ഷേ ഓരോരുത്തരും ഒരേ മെമ്മറിയിൽ നിന്നും ഉണ്ടാക്കുന്നു.
* സ്റ്റാക്ക് - ഒന്നിലധികം ടെൻസർമാരെ top of each other ഒരുമിക്കും ചേർത്ത് ഉണ്ടാക്കുന്നു (VStack) അല്ലെങ്കിൽ side by side ഒരുമിക്കും പ്രത്യേക പകർപ്പ് (hStack) ചേർത്ത് ഉണ്ടാക്കുന്നു.
* സ്വീസ് - ഒരു ടെൻസർമാരിൽ നിന്ന് എല്ലാ 1 ആകർഷണങ്ങളും നീക്കം ചെയ്യുന്നു
* അൺസ്വീസ് - ഒരു ലക്ഷ്യമായ ടെൻസർമാരിൽ 1 ഡിമൻഷൻ ചേർക്കുന്നു
* പർമ്യൂട്ട് - നിർവ്വചിത രീതിയിൽ ടെൻസർ ഡിമൻഷൻസുകൾ പെർമ്യൂട്ട് ചെയ്യുന്നു (അനുസ്വരിച്ച് മാറ്റുന്നു) എന്നതാണ് പർമ്യൂട്ട് എന്നത്

In [40]:
# Create a tensor 
N=torch.arange(1.,10.)
N,N.shape
# Here N having 9 elements at 1 dimensional with a size of 9 ---> (1)

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [45]:
# Add an Extra Dimension
N_reshape = N.reshape(1,9)
N_reshape[:,0]=6
N_reshape,N_reshape.shape
print(f"N_reshape : {N_reshape}\n N : {N}")
# As we know that from (1) Elements in N is reshaped in certain shape which is multiply in both ways to get the size of N. (1,9),(9,1),(3,3) = 9 (Row x Column)
# Else Eg : shape '[5, 3]' is invalid for input of size 9

N_reshape : tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]])
 N : tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# Change the View
N_view=N.view(1,9)
N_view[:,0]=5
print(f"N_view : {N_view}\n N : {N}")
# Changing Z changes N (because a view of a tensor shares the same memory as the orginal)

N_view : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
 N : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
#Stack tensor on top of each other
N_stack = torch.stack([N,N,N,N],dim=1)
N_stack,N_stack.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

**torch.Squeeze**

In [51]:
#torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor {N_reshape}\nPrevious Size  {N_reshape.shape}")
#Remove extra dimenstion from N_reshape
N_squeezed =N_reshape.squeeze()
print(f"New tensor {N_squeezed}\nNew Size  {N_squeezed.shape}")

Previous tensor tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Size  torch.Size([1, 9])
New tensor tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.])
New Size  torch.Size([9])


*torch.Unsqueeze*

In [55]:
#torch.unsqueeze()-adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor {N_squeezed}\nPrevious Size  {N_squeezed.shape}")
#Add an extra dimension with unsqueeze
N_unsqueez=N_squeezed.unsqueeze(dim=0)
print(f"New tensor {N_unsqueez}\nNew Size  {N_unsqueez.shape}")

Previous tensor tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Size  torch.Size([9])
New tensor tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Size  torch.Size([1, 9])


***torch.permute*** - rearrange the dimensions of a target tensor in a specified order

In [57]:
x_orginal = torch.rand(size=(224,225,3)) #Eg: [height,width,color_channel]
#Permute the orginal tensor to rearrange the axis (or dim) order
x_permuted=x_orginal.permute(2,0,1) #shifts axis (224) 0 -> 1, (225) 1 -> 2 , (3) 2 -> 0

print(f"Previous Size  {N_squeezed.shape}") #[height,width,color_channel]
print(f"New Size  {N_unsqueez.shape}") #[color_channel,height,width,]

Previous Size  torch.Size([9])
New Size  torch.Size([1, 9])


In [60]:
x_orginal[0,0,0] = 7289 
x_orginal[0,0,0] ,x_permuted[0,0,0]

(tensor(7289.), tensor(7289.))

**Indexing (Selecting data from tensors)**

Indexing with pytorch is similar to indexing with numpy

In [72]:
#Create a tensor
t=torch.arange(1,10).reshape(1,3,3)
t,t.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [64]:
# Let's Index on our new tensor

t[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
#Let's index on the middle bracket (dim=1)
t[0,1]

tensor([4, 5, 6])

In [73]:
#Let's index on the most inner bracket (Last dimension)
t[0,1,2]

tensor(6)

In [75]:
# You can also use ':' to select all of a target dimension
t[:,1]

tensor([[4, 5, 6]])

In [79]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
t[:,:,1]

tensor([[2, 5, 8]])

In [81]:
#Get all values of 0th dimension  but only 1 index value of 1st and 2nd dimension
t[:,1,1]

tensor([5])

In [82]:
#Get index0 of 0th dimension and 1st dimension and all values of 2nd dimension
t[0,0,:]

tensor([1, 2, 3])

In [84]:
#Index on t to return 9
print(t[0,2,2])

# index on t to return 3,6,9
print(t[0,:,2])

tensor(9)
tensor([3, 6, 9])
