<a href="https://colab.research.google.com/github/aynandu/Python-DeepLearning/blob/master/00_pytoruch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**00-Pytourch Fundamentals**

Resource Book : https://www.learnpytorch.io/00_pytorch_fundamentals/
Questions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


#Introduction to Tensors

###Creating tensors

PyTorch Tensors are Created Using 'torch.tensor()' : - https://pytorch.org/docs/stable/tensors.html

Tensor : - https://en.wikipedia.org/wiki/Tensor

#scalar = 1 , 
#Vector = 
        [
          1
          2] 
#matrix = 
      [
          1 2
          3 4
              ] 
#tesnor = 
      [
          [1 2] [3 2]
          [1 7] [5 4]
                    ]

In [6]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [12]:
#ndimention - scalar
scalar.ndim

0

In [13]:
#Size
scalar.shape

torch.Size([])

In [8]:
#Get Tensor Back as Python int
scalar.item()

7

In [9]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
#ndimention - Vector
vector.ndim

1

In [14]:
#size
vector.shape

torch.Size([2])

In [33]:
#Matrix
MATRIX =torch.tensor([[7,8],
                      [9,10],
                      [11,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [34]:
#ndimentions
MATRIX.ndim


2

In [20]:
MATRIX[0]

tensor([7, 8])

In [35]:
#Size
MATRIX.shape

torch.Size([3, 2])

In [45]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,3,8]]])
TENSOR
#pink parent has 1 child "blue"; blue parent has 4 (column) child "yellow";each yellow having 3 (row) child values. it becomes shape of (1,4,3)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [1, 3, 8]]])

In [31]:
#ndimenstion
TENSOR.ndim

3

In [43]:
#Size
TENSOR.shape

torch.Size([1, 4, 3])

#**Random Tensors**

###*Why random tensors?*
#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers better represent the data. 
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [54]:
#Create A Random Matric of size
random_tensor=torch.rand(2,3,2)
random_tensor

tensor([[[0.3376, 0.9624],
         [0.0719, 0.6790],
         [0.8229, 0.6481]],

        [[0.8376, 0.4996],
         [0.6118, 0.3192],
         [0.2769, 0.4486]]])

In [55]:
random_tensor.ndim

3

In [56]:
#Create a random tensor with  similar shape to an image tensor
rndm_image_size_tensor = torch.rand(size=(224,224,3)) #height ,width , color Channel (R,G,B)
rndm_image_size_tensor.shape ,rndm_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)