<a href="https://colab.research.google.com/github/aynandu/Python-DeepLearning/blob/master/00_pytoruch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**00-Pytourch Fundamentals**

Resource Book : https://www.learnpytorch.io/00_pytorch_fundamentals/
Questions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


#Introduction to Tensors

###Creating tensors

PyTorch Tensors are Created Using 'torch.tensor()' : - https://pytorch.org/docs/stable/tensors.html

Tensor : - https://en.wikipedia.org/wiki/Tensor

#scalar = 1 ,
#Vector =
        [
          1
          2]
#matrix =
      [
          1 2
          3 4
              ]
#tesnor =
      [
          [1 2] [3 2]
          [1 7] [5 4]
                    ]

In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
#ndimention - scalar
scalar.ndim

0

In [4]:
#Size
scalar.shape

torch.Size([])

In [5]:
#Get Tensor Back as Python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
#ndimention - Vector
vector.ndim

1

In [8]:
#size
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX =torch.tensor([[7,8],
                      [9,10],
                      [11,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [10]:
#ndimentions
MATRIX.ndim


2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
#Size
MATRIX.shape

torch.Size([3, 2])

In [13]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,3,8]]])
TENSOR
#pink parent has 1 child "blue"; blue parent has 4 (column) child "yellow";each yellow having 3 (row) child values. it becomes shape of (1,4,3)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [1, 3, 8]]])

In [14]:
#ndimenstion
TENSOR.ndim

3

In [15]:
#Size
TENSOR.shape

torch.Size([1, 4, 3])

#**Random Tensors**

###*Why random tensors?*
#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers better represent the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [24]:
#Create A Random Matric of size
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.9029, 0.4211, 0.6514, 0.1314],
         [0.8016, 0.1496, 0.3662, 0.5450],
         [0.4964, 0.6579, 0.1088, 0.0827]],

        [[0.8435, 0.5802, 0.1586, 0.4948],
         [0.1714, 0.9427, 0.7082, 0.5880],
         [0.1312, 0.2080, 0.1911, 0.0412]]])

In [17]:
random_tensor.ndim

3

In [18]:
#Create a random tensor with  similar shape to an image tensor
rndm_image_size_tensor = torch.rand(size=(224,224,3)) #height ,width , color Channel (R,G,B)
rndm_image_size_tensor.shape ,rndm_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and Ones

In [19]:
#Create a tensor  of all Zeros
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [28]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
print(random_tensor.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
