<a href="https://colab.research.google.com/github/aynandu/Python-DeepLearning/blob/master/00_pytoruch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**00-Pytourch Fundamentals**

Resource Book : https://www.learnpytorch.io/00_pytorch_fundamentals/
Questions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
#import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


#Introduction to Tensors

###Creating tensors

PyTorch Tensors are Created Using 'torch.tensor()' : - https://pytorch.org/docs/stable/tensors.html

Tensor : - https://en.wikipedia.org/wiki/Tensor

#scalar = 1 ,
#Vector =
        [
          1
          2]
#matrix =
      [
          1 2
          3 4
              ]
#tesnor =
      [
          [1 2] [3 2]
          [1 7] [5 4]
                    ]

In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
#ndimention - scalar
scalar.ndim

0

In [4]:
#Size
scalar.shape

torch.Size([])

In [5]:
#Get Tensor Back as Python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
#ndimention - Vector
vector.ndim

1

In [8]:
#size
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX =torch.tensor([[7,8],
                      [9,10],
                      [11,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [10]:
#ndimentions
MATRIX.ndim


2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
#Size
MATRIX.shape

torch.Size([3, 2])

In [13]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,3,8]]])
TENSOR
#pink parent has 1 child "blue"; blue parent has 4 (column) child "yellow";each yellow having 3 (row) child values. it becomes shape of (1,4,3)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5],
         [1, 3, 8]]])

In [14]:
#ndimenstion
TENSOR.ndim

3

In [15]:
#Size
TENSOR.shape

torch.Size([1, 4, 3])

#**Random Tensors**

###*Why random tensors?*
#####Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers better represent the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
#Create A Random Matric of size
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.9475, 0.2189, 0.0446, 0.1045],
         [0.6592, 0.8930, 0.7874, 0.2966],
         [0.0494, 0.0121, 0.1408, 0.3835]],

        [[0.3325, 0.4782, 0.1405, 0.4199],
         [0.1895, 0.9218, 0.5452, 0.4279],
         [0.1291, 0.0381, 0.4413, 0.7883]]])

In [17]:
random_tensor.ndim

3

In [18]:
#Create a random tensor with  similar shape to an image tensor
rndm_image_size_tensor = torch.rand(size=(224,224,3)) #height ,width , color Channel (R,G,B)
rndm_image_size_tensor.shape ,rndm_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and Ones

In [19]:
#Create a tensor  of all Zeros
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
print(random_tensor.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


Create a range of tensor and tensors - like

In [22]:
#use torch.arange()
#torch.range() is also having same function but it will be removed in upcoming updates use torch.arange() instead of that.
range_Num=torch.arange(start=0,end=1000,step=50) # no step means default step is 1
range_Num

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [23]:
# Creating a tensors like
ten_zeros=torch.zeros_like(input=range_Num)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Data Types

`Note : Tensor data type is the one of the 3 big errors you'll run into with Pytorch & Deep Learning`
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precesion in Computing : https://en.wikipedia.org/wiki/Precision_(computer_science)

In [24]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float32,# what datatype is the tensro (eg: float16,float32,float64)
                               device=None, #cpu,gpu,cuda
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
print(int_32_tensor)
value= float_32_tensor * int_32_tensor
print (f"value is {value} data type is {value.dtype}")

tensor([3, 6, 9], dtype=torch.int32)
value is tensor([ 9., 36., 81.]) data type is torch.float32


Get information from tensors (tensor attribute)

1. tensor not right datatype -  to  get datatype from a tensor, can use  `tensor.dtype`
2. tensor not right shape -  to  get shape from a tensor, can use  `tensor.shape`
1. tensor not on the right device -  to get device  from a tensor, can use  `tensor.device`

In [28]:
# Create a random tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9868, 0.2671, 0.9884, 0.2553],
        [0.7338, 0.0157, 0.8410, 0.1093],
        [0.6749, 0.9867, 0.5362, 0.4662]])

In [29]:
#Find out details about Some Tensor
print(f"Data Type : {some_tensor.dtype} | Shape : {some_tensor.shape} | Size : {some_tensor.size} |  Device : {some_tensor.device}")
# NB: some_tensor.size is a fun not attribute

Data Type : torch.float32 | Shape : torch.Size([3, 4]) | Size : <built-in method size of Tensor object at 0x7fdf64962890> |  Device : cpu


Maaipulating Tensor (tensor operations)

Tensor operations include :
* Addition
* Subtraction
* Multiplication (Element-wise)
* Division
* Matrix multplication



In [30]:
# Create a Tensor
tensor_manip = torch.tensor([2,4,10])
print(tensor_manip)
# Addition
print("\n Addition : " , tensor_manip+10)
# Multiply
print("\n Multiply : " , tensor_manip*10)
#Subtract
print("\n Subtract : " , tensor_manip-10)

tensor([ 2,  4, 10])

 Addition :  tensor([12, 14, 20])

 Multiply :  tensor([ 20,  40, 100])

 Subtract :  tensor([-8, -6,  0])


In [31]:
# Try out with PyTorch in-built function
# Addition
print("\n Addition : " , torch.add(tensor_manip,10))
# Subtract
print("\n Subtract : " , torch.sub(tensor_manip,10))
# Multiply
print("\n Multiply : " ,  torch.mul(tensor_manip,10))


 Addition :  tensor([12, 14, 20])

 Subtract :  tensor([-8, -6,  0])

 Multiply :  tensor([ 20,  40, 100])


Matrix Multiplication

Two main ways of performing Multiplication in neural networks and deep learning

1. Element - wise multiplication
2. Matrix multiplication (dot product)

More Infromation on Multiplying Matrices : https://www.mathsisfun.com/algebra/matrix-multiplying.html

and https://www.matrixmultiplication.xyz

There are two main rules that performing matrix multiplication to satisfy :
1. The **inner dimension** must Match :
    * (3,2) @ (3,2) won't work  --> inner dimension  2 (columns) x 3 (rows)
    * (2,3) @ (3,2) will work   --> inner dimension  3 (columns) x 3 (rows)
    * (3,2) @ (2,3) will work   --> inner dimension  2 (columns) x 2 (rows)
2. The resulting Matrixs have he shape of the **outer dimensions** :
    * (2,3) @ (3,2) will work   --> outer dimension  2 (rows) x 2 (columns)
    * (3,2) @ (2,3) will work   --> outer dimension  3 (rows) x 3 (columns)

In [32]:
print("Normal random Matrix :\n",torch.rand(3,5))
print("\nResulting Matrix :")
torch.matmul(torch.rand(3,5),torch.rand(5,3)) #The resulting Matrixs have he shape of the **outer dimensions** :

Normal random Matrix :
 tensor([[0.1220, 0.1678, 0.5268, 0.4451, 0.4860],
        [0.8258, 0.5726, 0.8607, 0.4552, 0.5310],
        [0.5961, 0.5621, 0.3765, 0.6070, 0.1216]])

Resulting Matrix :


tensor([[0.8420, 1.8799, 1.9014],
        [0.7234, 1.5344, 1.9409],
        [1.0411, 1.7917, 1.9238]])

In [33]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])
print(tensor, "*" , tensor)
print("Equals = ",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals =  tensor([1, 4, 9])


In [34]:
#Matrix Multiplication
print (torch.matmul(tensor,tensor))
print (torch.dot(tensor,tensor))

tensor(14)
tensor(14)


In [35]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 328 µs, sys: 65 µs, total: 393 µs
Wall time: 400 µs


In [36]:
%%time
print(torch.matmul(tensor,tensor))

tensor(14)
CPU times: user 258 µs, sys: 0 ns, total: 258 µs
Wall time: 266 µs


One of the Common Errors in deep Learning : shape Errors

In [39]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A,tensor_B) #torch.mm is torch.matmul
# Cell No:27 - Error 2-- shape error

RuntimeError: ignored

In [40]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To Fix our tensor shape issues , we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [41]:
torch.mm(tensor_A,tensor_B.T) , torch.mm(tensor_A,tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [42]:
# Matrix Multiplication works when tensor_B is transposed :
print(f"Orginal Shapes: tensor_A = {tensor_A.shape} tensor_B = {tensor.shape}")
print(f"New Shapes: tensor_A ={tensor_A.shape} (same as above) tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <-- Inner dimension must match")
print("\nOutput")
output= torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"\nOut Shape  : {output.shape}")

Orginal Shapes: tensor_A = torch.Size([3, 2]) tensor_B = torch.Size([3])
New Shapes: tensor_A =torch.Size([3, 2]) (same as above) tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <-- Inner dimension must match

Output
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Out Shape  : torch.Size([3, 3])


Finding the min, max, mean, sum etc (tensor aggregation)

In [43]:
# Create a Tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
#Find Max & Min ,sum
print(f"min : {torch.min(x)}\nMax : {torch.max(x)} \nsum {torch.sum(x)} also use this method {x.sum()}")

min : 0
Max : 90 
sum 450 also use this method 450


In [45]:
#Find Mean -  note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
#print(f"mean: {torch.mean(x)}") --> Error : mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

# Cell No:27 - Error 1- Right Data Type error

(tensor(45.), tensor(45.))

Finding the Positional min and max

In [46]:
#find the position in tensor  that has the minimum value with argmin() --> returns index position of target tensor wehere the minimum value occurs
print(x.argmin(),x[0])
#find the position in tensor  that has the maximum value with argmin() --> returns index position of target tensor wehere the maximum value occurs
print(x.argmax(),x[9])

tensor(0) tensor(0)
tensor(9) tensor(90)


**Reshaping , stacking , squeezing and unsqueezing tensors**

* Reshaping - reshapes an input tensor to a defined shape
* View  - Return a view of an input tensor of certain shape but keep the same memory as the Orginal tensor.
* Stacking - Combine multiple tensors on the top of each other (vstack) or side by side (hstack);
    * torch.stack :- https://pytorch.org/docs/stable/generated/torch.stack.html
    * Vstack :- https://pytorch.org/docs/stable/generated/torch.vstack.html   (Stack tensors in sequence vertically (row wise).)
    * hstack :- https://pytorch.org/docs/stable/generated/torch.hstack.html   (Stack tensors in sequence horizontally (column wise).)

* Squeeze - removes all 1 dimensions from a tensor ; https://pytorch.org/docs/stable/generated/torch.squeeze.html
* Unsqueeze - Add a 1 domension to a target tensor
* Permute - Return  a View of the input with dimensions permuted (swapped) in a certain way


* രീഷേപ് - ഇന്പുട്ട് ടെൻസർ ഒരു നിർവ്വചിത ആകർഷണത്തിലേക്ക് രീഷേപ് ചെയ്യുന്നു
* വ്യൂ - ഒരു ഇൻപുട്ട് ടെൻസർ നിരീക്ഷണരൂപത്തിൽ ഒരു കൊടുത്ത ആകർഷണം ലഭിക്കുന്നു, പക്ഷേ ഓരോരുത്തരും ഒരേ മെമ്മറിയിൽ നിന്നും ഉണ്ടാക്കുന്നു.
* സ്റ്റാക്ക് - ഒന്നിലധികം ടെൻസർമാരെ top of each other ഒരുമിക്കും ചേർത്ത് ഉണ്ടാക്കുന്നു (VStack) അല്ലെങ്കിൽ side by side ഒരുമിക്കും പ്രത്യേക പകർപ്പ് (hStack) ചേർത്ത് ഉണ്ടാക്കുന്നു.
* സ്വീസ് - ഒരു ടെൻസർമാരിൽ നിന്ന് എല്ലാ 1 ആകർഷണങ്ങളും നീക്കം ചെയ്യുന്നു
* അൺസ്വീസ് - ഒരു ലക്ഷ്യമായ ടെൻസർമാരിൽ 1 ഡിമൻഷൻ ചേർക്കുന്നു
* പർമ്യൂട്ട് - നിർവ്വചിത രീതിയിൽ ടെൻസർ ഡിമൻഷൻസുകൾ പെർമ്യൂട്ട് ചെയ്യുന്നു (അനുസ്വരിച്ച് മാറ്റുന്നു) എന്നതാണ് പർമ്യൂട്ട് എന്നത്

In [47]:
# Create a tensor
N=torch.arange(1.,10.)
N,N.shape
# Here N having 9 elements at 1 dimensional with a size of 9 ---> (1)

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
# Add an Extra Dimension
N_reshape = N.reshape(1,9)
N_reshape[:,0]=6
N_reshape,N_reshape.shape
print(f"N_reshape : {N_reshape}\n N : {N}")
# As we know that from (1) Elements in N is reshaped in certain shape which is multiply in both ways to get the size of N. (1,9),(9,1),(3,3) = 9 (Row x Column)
# Else Eg : shape '[5, 3]' is invalid for input of size 9

N_reshape : tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]])
 N : tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.])


In [49]:
# Change the View
N_view=N.view(1,9)
N_view[:,0]=5
print(f"N_view : {N_view}\n N : {N}")
# Changing Z changes N (because a view of a tensor shares the same memory as the orginal)

N_view : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
 N : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [50]:
#Stack tensor on top of each other
N_stack = torch.stack([N,N,N,N],dim=1)
N_stack,N_stack.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

**torch.Squeeze**

In [51]:
#torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor {N_reshape}\nPrevious Size  {N_reshape.shape}")
#Remove extra dimenstion from N_reshape
N_squeezed =N_reshape.squeeze()
print(f"New tensor {N_squeezed}\nNew Size  {N_squeezed.shape}")

Previous tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Size  torch.Size([1, 9])
New tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Size  torch.Size([9])


*torch.Unsqueeze*

In [52]:
#torch.unsqueeze()-adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor {N_squeezed}\nPrevious Size  {N_squeezed.shape}")
#Add an extra dimension with unsqueeze
N_unsqueez=N_squeezed.unsqueeze(dim=0)
print(f"New tensor {N_unsqueez}\nNew Size  {N_unsqueez.shape}")

Previous tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Size  torch.Size([9])
New tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Size  torch.Size([1, 9])


***torch.permute*** - rearrange the dimensions of a target tensor in a specified order

In [53]:
x_orginal = torch.rand(size=(224,225,3)) #Eg: [height,width,color_channel]
#Permute the orginal tensor to rearrange the axis (or dim) order
x_permuted=x_orginal.permute(2,0,1) #shifts axis (224) 0 -> 1, (225) 1 -> 2 , (3) 2 -> 0

print(f"Previous Size  {N_squeezed.shape}") #[height,width,color_channel]
print(f"New Size  {N_unsqueez.shape}") #[color_channel,height,width,]

Previous Size  torch.Size([9])
New Size  torch.Size([1, 9])


In [54]:
x_orginal[0,0,0] = 7289
x_orginal[0,0,0] ,x_permuted[0,0,0]

(tensor(7289.), tensor(7289.))

**Indexing (Selecting data from tensors)**

Indexing with pytorch is similar to indexing with numpy

In [55]:
#Create a tensor
t=torch.arange(1,10).reshape(1,3,3)
t,t.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [56]:
# Let's Index on our new tensor

t[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [57]:
#Let's index on the middle bracket (dim=1)
t[0,1]

tensor([4, 5, 6])

In [58]:
#Let's index on the most inner bracket (Last dimension)
t[0,1,2]

tensor(6)

In [59]:
# You can also use ':' to select all of a target dimension
t[:,1]

tensor([[4, 5, 6]])

In [60]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
t[:,:,1]

tensor([[2, 5, 8]])

In [61]:
#Get all values of 0th dimension  but only 1 index value of 1st and 2nd dimension
t[:,1,1]

tensor([5])

In [62]:
#Get index0 of 0th dimension and 1st dimension and all values of 2nd dimension
t[0,0,:]

tensor([1, 2, 3])

In [63]:
#Index on t to return 9
print(t[0,2,2])

# index on t to return 3,6,9
print(t[0,:,2])

tensor(9)
tensor([3, 6, 9])


**Pytorch Tensors & Numpy**

Numpy is a popular  scientific Python numerical computing library.
And because of this,Pytorch has functionality to interact with it.
* Data in Numpy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html
    

In [64]:
# Numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor_array=torch.from_numpy(array) # Warning : when converting from numpy -> pytorch,pytorch reflects numpy's  default data type of float64 unless specified otherwise
tensor_array

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [65]:
#Change the value of array, whath will this do to 'tensor'?
array=array+1
array,tensor_array

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
#Tensor  to Numpy array
tensor = torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducbility (trying to take random out of random)**

In short how a  neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again ...`

*To reduce the randomness in neural networks* and Pytorch comes the concept of a **random seed**.
Essentially what the random seed does is  "flavour" thr randomness.

Resource :
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [67]:
#Create teo random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A ,"\n", random_tensor_B)
print(random_tensor_A ==random_tensor_B)

tensor([[0.0992, 0.4133, 0.8645, 0.2041],
        [0.4275, 0.8773, 0.1250, 0.9706],
        [0.3812, 0.3329, 0.0929, 0.6154]]) 
 tensor([[0.4599, 0.8762, 0.4159, 0.8890],
        [0.0068, 0.3023, 0.6832, 0.6564],
        [0.4613, 0.1536, 0.4057, 0.9618]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [68]:
# Lets Make Some Random but reproducible  tensors

# Set the random seed

randomSeed=42
torch.manual_seed(randomSeed) # --> this random Seed function works only one line below. so repeat it whe ever you require.
random_tensor_C = torch.rand(3,4)

torch.manual_seed(randomSeed) # --> this random Seed function works only one line below. so repeat it whe ever you require.
random_tensor_D = torch.rand(3,4)

print(random_tensor_C ,"\n", random_tensor_D)
print(random_tensor_C ==random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Running tensors  and pytorch objects on the GPUs (and making faster computations)**

GPUs = faster computation on numbers,thanks to CUDA + NVIDIA hardware +Pytorch working behind the scenes to make everything hunky dory (good)


1. Getting a GPU
    1. Easiest - Use Google Colab for a free GPU (Options to upgrade as well)
    2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options ..., see this post for  what option to ger: https://timdettmers.com/category/deep-learning/
    3. use cloud computing - GCP,AWS,Azure these services allow you to rent  computers on the cloud and access them.
    
For 2,3 Pytorch + GPU drivers (CUDA) takes a  littel bit of setting up,to do this ,refer to Pytorch setup documentation : https://pytorch.org/get-started/locally/

In [72]:
!nvidia-smi

Sun Jun 25 09:40:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

2. Getting PyTorch to run on the GPU

Once you've got a GPU ready to access, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the torch.cuda package.

Rather than talk about it, let's try it out.

You can test if PyTorch has access to a GPU using torch.cuda.is_available().

In [69]:
torch.cuda.is_available()  # Cuda is an Nvidia GPU

True

If the above outputs True, PyTorch can see and use the GPU, if it outputs False, it can't see the GPU and in that case, you'll have to go back through the installation steps.

Now, let's say you wanted to setup your code so it ran on CPU or the GPU if it was available.

That way, if you or someone decides to run your code, it'll work regardless of the computing device they're using.

Let's create a device variable to store what kind of device is available.

In [70]:
# Set device type
device='cuda' if torch.cuda.is_available() else "cpu"
device

'cuda'

If the above output "cuda" it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output "cpu", our PyTorch code will stick with the CPU.

Note: In PyTorch, it's best practice to write device agnostic code. This means code that'll run on CPU (always available) or GPU (if available).

If you want to do faster computing you can use a GPU but if you want to do much faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using torch.cuda.device_count().

In [71]:
# Count number of devices
torch.cuda.device_count()

1

#3. Putting tensors (and models) on GPU
###The Reason  we want our tensors/models on the GPU results in faster computation

In [73]:
# Create a Tensor (default on CPU)
tensor=torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [74]:
# MOve Tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#4.Moving Tensors back to CPU

In [76]:
#If the tensor is on GPU,can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [77]:
# To fix the GPU tensor with numpy issue, we can first set it to the CPU
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Excercises & Extra-Curriculum
###see excercises for this notebook here :  https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

check out here : https://github.com/aynandu/Python-DeepLearning/blob/master/00_PyTorch_Fundamentals_Excercises.ipynb