Matrix Property

In [20]:
import numpy as np  # For Algebric Expressions
import matplotlib.pyplot as plt  # for Graphical Representation
import torch 

In [21]:
A=np.array([[3,4],[5,6],[7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [22]:
b=np.array([1,2])
b

array([1, 2])

In [23]:
np.dot(A,b)

array([11, 17, 23])

In [24]:
B=np.array([[1,9],[2,0]])
B

array([[1, 9],
       [2, 0]])

In [25]:
np.dot(A,B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [34]:
Z=np.array([[0,1,2],[3,4,5],[6,7,8]])
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
W=np.array([[-1,0],[1,1],[-2,2]])
W

array([[-1,  0],
       [ 1,  1],
       [-2,  2]])

In [35]:
np.dot(Z,W)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])

Matricx Inversion

In [36]:
X=np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [37]:
Xlinv = np.linalg.inv(X)
Xlinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [38]:
y=np.array([4,-7])
y

array([ 4, -7])

In [40]:
w = np.dot(Xlinv,y)
w

array([-1.,  4.])

Show that  y=Xw;
here y=[4,-7]
prove LHS = RHS

In [41]:
np.dot(X,w)

array([ 4., -7.])

Orthogonal Matrices

In [78]:
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [79]:
colum_1=I[:,0] #I[:(all),Column]=>all column data of index  I[row,(all):]  =>all row data of index 
colum_1

array([1, 0, 0])

In [48]:
colum_2=I[:,1]
colum_2

array([0, 1, 0])

In [49]:
colum_3=I[:,2]
colum_3

array([0, 0, 1])

In [50]:
np.dot(colum_1,colum_2) #colm1*colm2 = 0

0

In [51]:
np.dot(colum_1,colum_3)#colm1*colm3 = 0

0

In [52]:
np.dot(colum_2,colum_3) #colm3*colm2 = 0

0

In [53]:
np.linalg.norm(colum_1) #colum1[0,0]+colum1[0,1]+colum1[0,2] = 1

1.0

In [54]:
np.linalg.norm(colum_2) # ''

1.0

In [55]:
np.linalg.norm(colum_3) # ''

1.0

Excercise

In [56]:
K=torch.tensor([[2/3,1/3,2/3],[-2/3,2/3,1/3],[1/3,2/3,-2/3]])
K

tensor([[ 0.6667,  0.3333,  0.6667],
        [-0.6667,  0.6667,  0.3333],
        [ 0.3333,  0.6667, -0.6667]])

In [63]:
kcol_1=K[:,0]  #K[:(all),Column]=>all column data of index  K[row,(all):]  =>all row data of index 
kcol_1

tensor([ 0.6667, -0.6667,  0.3333])

In [65]:
kcol_2=K[:,1]
kcol_2

tensor([0.3333, 0.6667, 0.6667])

In [60]:
kcol_3=K[:,2]
kcol_3

tensor([ 0.6667,  0.3333, -0.6667])

In [66]:
torch.dot(kcol_1,kcol_2)

tensor(0.)

In [67]:
torch.dot(kcol_1,kcol_3)

tensor(0.)

In [68]:
torch.dot(kcol_3,kcol_2)

tensor(0.)

In [69]:
torch.norm(kcol_1)

tensor(1.)

In [70]:
torch.norm(kcol_2)

tensor(1.)

In [71]:
torch.norm(kcol_3)

tensor(1.)